In [1]:
import pandas as pd
import math

In [ ]:
def read_csv_file(filename):
    return pd.read_csv(filename) #df

In [45]:
df = pd.read_csv('train.csv')

In [48]:
df.head()


employee_id         department     region         education gender  \
0        65438  Sales & Marketing   region_7  Master's & above      f   
1        65141         Operations  region_22        Bachelor's      m   
2         7513  Sales & Marketing  region_19        Bachelor's      m   
3         2542  Sales & Marketing  region_23        Bachelor's      m   
4        48945         Technology  region_26        Bachelor's      m   

  recruitment_channel  no_of_trainings  age  previous_year_rating  \
0            sourcing                1   35                   5.0   
1               other                1   30                   5.0   
2            sourcing                1   34                   3.0   
3               other                2   39                   1.0   
4               other                1   45                   3.0   

   length_of_service  KPIs_met >80%  awards_won?  avg_training_score  \
0                  8              1            0                  49   
1                  4              0            0                  60   
2                  7              0            0                  50   
3                 10              0            0                  50   
4                  2              0            0                  73   

   is_promoted  
0            0  
1            0  
2            0  
3            0  
4            0

In [4]:
print(len(df))
print(len (df['employee_id'].unique()))

54808
54808


In [5]:
len(df['department'].unique())

9

In [7]:
len(df['region'].unique())

34

In [8]:
df['education'].unique()

array(["Master's & above", "Bachelor's", nan, 'Below Secondary'],
      dtype=object)

In [9]:
new_df = df.drop(columns =['employee_id' , 'recruitment_channel', 'age' ,'gender','education'], axis = 0)

In [10]:
new_df.head()


department     region  no_of_trainings  previous_year_rating  \
0  Sales & Marketing   region_7                1                   5.0   
1         Operations  region_22                1                   5.0   
2  Sales & Marketing  region_19                1                   3.0   
3  Sales & Marketing  region_23                2                   1.0   
4         Technology  region_26                1                   3.0   

   length_of_service  KPIs_met >80%  awards_won?  avg_training_score  \
0                  8              1            0                  49   
1                  4              0            0                  60   
2                  7              0            0                  50   
3                 10              0            0                  50   
4                  2              0            0                  73   

   is_promoted  
0            0  
1            0  
2            0  
3            0  
4            0

In [49]:
new_df.isnull().sum()

department                 0
region                     0
no_of_trainings            0
previous_year_rating    4124
length_of_service          0
KPIs_met >80%              0
awards_won?                0
avg_training_score         0
is_promoted                0
dtype: int64

In [115]:
new_df[new_df['previous_year_rating'].isnull() & new_df['is_promoted'] == 1]['previous_year_rating'] = 5.0



c:\users\kanwal\miniconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [51]:
X = [] 
X = new_df.values.tolist()


In [52]:
k=0
for row in X:
    if math.isnan(row[3]) == True:
            k= k+1
print(k)

4124


In [53]:
for row in X:
    if math.isnan(row[3]) == True and row[8] == 1:
        row[3] = 5
    elif math.isnan(row[3]) == True:
        row[3] = 3
        

In [54]:
import numpy as np
X = np.array(X)
labels = X[:,-1]
X = X[:,:-1]

labels

array(['0', '0', '0', ..., '0', '0', '0'], dtype='<U17')

In [55]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

lbl = LabelEncoder()
enc = OneHotEncoder(sparse=False)
X[:,0] = lbl.fit_transform(X[:,0])

In [56]:
integer_encoded = X[:,0].reshape(len(X[:,0]), 1)
onehot_encoded = enc.fit_transform(integer_encoded)
onehot_encoded = np.array(onehot_encoded)
onehot_encoded
X
new_X = np.append(X[:,1:],onehot_encoded, axis = 1)
new_X[0]

array(['region_7', '1', '5.0', '8', '1', '0', '49', '0.0', '0.0', '0.0',
       '0.0', '0.0', '0.0', '0.0', '1.0', '0.0'], dtype='<U32')

In [57]:
lbl = LabelEncoder()
enc = OneHotEncoder(sparse=False)
new_X[:,0] = lbl.fit_transform(new_X[:,0])
integer_encoded = new_X[:,0].reshape(len(new_X[:,0]), 1)
onehot_encoded = enc.fit_transform(integer_encoded)
onehot_encoded = np.array(onehot_encoded)
onehot_encoded
new_X = np.append(new_X[:,1:],onehot_encoded, axis = 1)
new_X[0]

array(['1', '5.0', '8', '1', '0', '49', '0.0', '0.0', '0.0', '0.0', '0.0',
       '0.0', '0.0', '1.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0',
       '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0',
       '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0',
       '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '1.0',
       '0.0', '0.0'], dtype='<U32')

In [20]:
final_X = []
for row in new_X:
    for i in range(len(row)):
        i = int(i)
    final_X.append(row)
    
final_X[0]

array(['1', '3', '8', '1', '0', '49', '0.0', '0.0', '0.0', '0.0', '0.0',
       '0.0', '0.0', '1.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0',
       '0.0', '0.0', '1.0', '0.0'], dtype='<U32')

In [58]:
from sklearn.model_selection import train_test_split

X_train, X_valid , y_train, y_test = train_test_split(new_X, labels, test_size =0.1, shuffle=True)

In [59]:
X_train.shape

(49327, 49)

In [23]:
y_train.shape

(49327,)

In [25]:
from sklearn.ensemble import RandomForestClassifier 
classifier = RandomForestClassifier()
classifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [37]:
from sklearn import tree 
classifier = tree.DecisionTreeClassifier()
classifier.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [38]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

tprediction = classifier.predict(X_valid)

print(accuracy_score(y_test, tprediction))
print(classification_report(y_test, tprediction))
print(confusion_matrix(y_test, tprediction))

0.9430760810071155
             precision    recall  f1-score   support

          0       0.95      0.99      0.97      5009
          1       0.85      0.41      0.56       472

avg / total       0.94      0.94      0.93      5481

[[4974   35]
 [ 277  195]]


In [35]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

cprediction = classifier.predict(X_valid)

print(accuracy_score(y_test, cprediction))
print(classification_report(y_test, cprediction))
print(confusion_matrix(y_test, cprediction))



0.942893632548805
             precision    recall  f1-score   support

          0       0.95      0.99      0.97      5009
          1       0.85      0.41      0.55       472

avg / total       0.94      0.94      0.93      5481

[[4974   35]
 [ 278  194]]


In [41]:
from sklearn.svm import SVC

model = SVC(C=10, kernel='rbf')
model.fit(X_train, y_train)

SVC(C=10, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [42]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

prediction = model.predict(X_valid)

print(accuracy_score(y_test, prediction))
print(classification_report(y_test, prediction))
print(confusion_matrix(y_test, prediction))


0.946360153256705
             precision    recall  f1-score   support

          0       0.94      1.00      0.97      5009
          1       0.99      0.38      0.55       472

avg / total       0.95      0.95      0.94      5481

[[5007    2]
 [ 292  180]]


In [60]:
from sklearn.svm import SVC

model = SVC()
model.fit(X_train, y_train)

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

prediction = model.predict(X_valid)

print(accuracy_score(y_test, prediction))
print(classification_report(y_test, prediction))
print(confusion_matrix(y_test, prediction))


0.9396095602992155
             precision    recall  f1-score   support

          0       0.94      1.00      0.97      4997
          1       0.99      0.32      0.48       484

avg / total       0.94      0.94      0.93      5481

[[4996    1]
 [ 330  154]]


In [187]:
prediction = model.predict(X_valid)

In [188]:
prediction[0]

'0'

In [191]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, prediction)

0.9520160554643313

In [70]:
test_df = pd.read_csv('test.csv')

In [71]:
test_df.head()
new_test_df = test_df.drop(columns =['employee_id' , 'recruitment_channel', 'age' ,'gender','education'], axis = 0)
new_test_df.head()

department     region  no_of_trainings  previous_year_rating  \
0         Technology  region_26                1                   NaN   
1                 HR   region_4                1                   3.0   
2  Sales & Marketing  region_13                1                   1.0   
3        Procurement   region_2                3                   2.0   
4            Finance  region_29                1                   4.0   

   length_of_service  KPIs_met >80%  awards_won?  avg_training_score  
0                  1              1            0                  77  
1                  5              0            0                  51  
2                  4              0            0                  47  
3                  9              0            0                  65  
4                  7              0            0                  61

In [72]:
len(new_test_df['department'].unique())

9

In [73]:
len(new_test_df['region'].unique())

34

In [74]:
new_test_df.isnull().sum()

department                 0
region                     0
no_of_trainings            0
previous_year_rating    1812
length_of_service          0
KPIs_met >80%              0
awards_won?                0
avg_training_score         0
dtype: int64

In [75]:
X_test_1 = [] 
X_test_1 = new_test_df.values.tolist()

k=0
for row in X_test_1:
    if math.isnan(row[3]) == True:
            k= k+1
print(k)

for row in X_test_1:
    if math.isnan(row[3]) == True:
        row[3] = 3
        
k=0
for row in X_test_1:
    if math.isnan(row[3]) == True:
            k= k+1
print(k)


1812
0


In [76]:
X_test_1[0]

['Technology', 'region_26', 1, 3, 1, 1, 0, 77]

In [77]:
X_test_1 = np.array(X_test_1)
X_test_1.shape

(23490, 8)

In [78]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

lbl = LabelEncoder()
enc = OneHotEncoder(sparse=False)
X_test_1[:,0] = lbl.fit_transform(X_test_1[:,0])

integer_encoded = X_test_1[:,0].reshape(len(X_test_1[:,0]), 1)
onehot_encoded = enc.fit_transform(integer_encoded)
onehot_encoded = np.array(onehot_encoded)
onehot_encoded

new_X_test = np.append(X_test_1[:,1:],onehot_encoded, axis = 1)
new_X_test[0]

array(['region_26', '1', '3', '1', '1', '0', '77', '0.0', '0.0', '0.0',
       '0.0', '0.0', '0.0', '0.0', '0.0', '1.0'], dtype='<U32')

In [79]:


lbl = LabelEncoder()
enc = OneHotEncoder(sparse=False)
new_X_test[:,0] = lbl.fit_transform(new_X_test[:,0])
integer_encoded = new_X_test[:,0].reshape(len(new_X_test[:,0]), 1)
onehot_encoded = enc.fit_transform(integer_encoded)
onehot_encoded = np.array(onehot_encoded)
onehot_encoded
new_X_test = np.append(new_X_test[:,1:],onehot_encoded, axis = 1)
new_X_test[0]

array(['1', '3', '1', '1', '0', '77', '0.0', '0.0', '0.0', '0.0', '0.0',
       '0.0', '0.0', '0.0', '1.0', '0.0', '0.0', '0.0', '0.0', '0.0',
       '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0',
       '0.0', '0.0', '0.0', '0.0', '1.0', '0.0', '0.0', '0.0', '0.0',
       '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0',
       '0.0', '0.0'], dtype='<U32')

In [80]:
new_X_test.shape

(23490, 49)

In [81]:
pred_test = model.predict(new_X_test)

In [82]:
pred_test

array(['0', '0', '0', ..., '0', '0', '1'], dtype='<U17')

In [83]:
for i in pred_test:
    file = open('result_new.txt' , 'a+')
    file.write(i+'\n')

In [84]:
import keras
from keras.layers import BatchNormalization
from keras.layers.core import Flatten,Dense,Dropout, Activation, Lambda
from keras.models import Model, Sequential
from keras.optimizers import Adam,SGD
from keras.callbacks import TensorBoard

Using TensorFlow backend.


In [92]:
model = Sequential()
#model.add(Lambda(lambda x: x , input_shape = (24)))
#model.add(Lambda(lambda x: x+0.1 , input_shape = (64,64,3)))
#model.add(Flatten())
model.add(BatchNormalization(input_shape=(49,)))
model.add(Dense(1000))
model.add(Activation('relu'))


#model.add(Dropout(0.2))
model.add(BatchNormalization())
model.add(Dense(500))
model.add(Activation('relu'))
#model.add(Dropout(0.2))
#model.add(BatchNormalization())
model.add(Dense(50))
model.add(Activation('relu'))

model.add(Dense(1))
model.add(Activation('sigmoid'))
model.compile(optimizer = 'Adam' , loss = 'binary_crossentropy', metrics=['accuracy'])

In [94]:
model.fit(X_train, y_train, epochs=10, verbose =1, validation_data=(X_valid, y_test), batch_size =64)

Train on 49327 samples, validate on 5481 samples
Epoch 1/10
49327/49327 [==============================] - 20s 397us/step - loss: 0.1835 - acc: 0.9364 - val_loss: 0.1833 - val_acc: 0.9371
Epoch 2/10
49327/49327 [==============================] - 20s 398us/step - loss: 0.1732 - acc: 0.9391 - val_loss: 0.1762 - val_acc: 0.9378
Epoch 3/10
49327/49327 [==============================] - 21s 422us/step - loss: 0.1692 - acc: 0.9399 - val_loss: 0.1747 - val_acc: 0.9376
Epoch 4/10
49327/49327 [==============================] - 20s 398us/step - loss: 0.1673 - acc: 0.9402 - val_loss: 0.1687 - val_acc: 0.9398
Epoch 5/10
49327/49327 [==============================] - 20s 400us/step - loss: 0.1649 - acc: 0.9406 - val_loss: 0.1714 - val_acc: 0.9403
Epoch 6/10
49327/49327 [==============================] - 21s 429us/step - loss: 0.1621 - acc: 0.9415 - val_loss: 0.1747 - val_acc: 0.9385
Epoch 7/10
49327/49327 [==============================] - 20s 408us/step - loss: 0.1608 - acc: 0.9410 - val_loss: 0.1

KeyboardInterrupt: 

In [95]:
model.save('model.h5')

In [106]:
pred = model.predict(new_X_test)


In [107]:

pred = (pred >= 0.5).astype(int)


In [113]:
pred = pred.reshape(-1)
pred.shape
pred[0]

0

In [114]:
for i in pred:
    file = open('neural.txt','a+')
    file.write(str(i)+'\n')