In [1]:
import pandas as pd
import math

In [2]:
def read_csv_file(filename):
    return pd.read_csv(filename) #df

In [37]:
df = pd.read_csv('train.csv')

In [38]:
df.head()
df.corr()

employee_id  no_of_trainings       age  \
employee_id              1.000000        -0.005121  0.000437   
no_of_trainings         -0.005121         1.000000 -0.081278   
age                      0.000437        -0.081278  1.000000   
previous_year_rating     0.004533        -0.063126  0.006008   
length_of_service        0.001274        -0.057275  0.657111   
KPIs_met >80%           -0.002501        -0.045576 -0.025592   
awards_won?              0.008420        -0.007628 -0.008169   
avg_training_score      -0.000586         0.042517 -0.048380   
is_promoted              0.001206        -0.024896 -0.017166   

                      previous_year_rating  length_of_service  KPIs_met >80%  \
employee_id                       0.004533           0.001274      -0.002501   
no_of_trainings                  -0.063126          -0.057275      -0.045576   
age                               0.006008           0.657111      -0.025592   
previous_year_rating              1.000000           0.000253       0.351578   
length_of_service                 0.000253           1.000000      -0.077693   
KPIs_met >80%                     0.351578          -0.077693       1.000000   
awards_won?                       0.027738          -0.039927       0.097000   
avg_training_score                0.075139          -0.038122       0.078391   
is_promoted                       0.159320          -0.010670       0.221582   

                      awards_won?  avg_training_score  is_promoted  
employee_id              0.008420           -0.000586     0.001206  
no_of_trainings         -0.007628            0.042517    -0.024896  
age                     -0.008169           -0.048380    -0.017166  
previous_year_rating     0.027738            0.075139     0.159320  
length_of_service       -0.039927           -0.038122    -0.010670  
KPIs_met >80%            0.097000            0.078391     0.221582  
awards_won?              1.000000            0.072138     0.195871  
avg_training_score       0.072138            1.000000     0.181147  
is_promoted              0.195871            0.181147     1.000000

In [39]:
print(len(df))
print(len (df['employee_id'].unique()))

54808
54808


In [40]:
len(df['department'].unique())

9

In [41]:
len(df['region'].unique())

34

In [42]:
df['education'].unique()

array(["Master's & above", "Bachelor's", nan, 'Below Secondary'],
      dtype=object)

In [80]:
new_df = df.drop(columns =['employee_id' , 'recruitment_channel', 'age' ,'gender','region'], axis = 0)

In [81]:
new_df.head()


department         education  no_of_trainings  previous_year_rating  \
0  Sales & Marketing  Master's & above                1                   5.0   
1         Operations        Bachelor's                1                   5.0   
2  Sales & Marketing        Bachelor's                1                   3.0   
3  Sales & Marketing        Bachelor's                2                   1.0   
4         Technology        Bachelor's                1                   3.0   

   length_of_service  KPIs_met >80%  awards_won?  avg_training_score  \
0                  8              1            0                  49   
1                  4              0            0                  60   
2                  7              0            0                  50   
3                 10              0            0                  50   
4                  2              0            0                  73   

   is_promoted  
0            0  
1            0  
2            0  
3            0  
4            0

In [82]:
new_df['education'] = new_df['education'].fillna(value='Bachelor\'s', axis=0)

In [83]:
new_df.isnull().sum()

department                 0
education                  0
no_of_trainings            0
previous_year_rating    4124
length_of_service          0
KPIs_met >80%              0
awards_won?                0
avg_training_score         0
is_promoted                0
dtype: int64

In [84]:
new_df[new_df['previous_year_rating'].isnull() & new_df['is_promoted'] == 1]['previous_year_rating']



66      NaN
67      NaN
84      NaN
542     NaN
566     NaN
639     NaN
694     NaN
974     NaN
1085    NaN
1179    NaN
1209    NaN
1455    NaN
1725    NaN
1921    NaN
2107    NaN
2134    NaN
2510    NaN
2581    NaN
2605    NaN
2783    NaN
3157    NaN
3192    NaN
3300    NaN
3374    NaN
3402    NaN
3715    NaN
3763    NaN
3805    NaN
3864    NaN
3969    NaN
         ..
50229   NaN
50890   NaN
51106   NaN
51200   NaN
51260   NaN
51380   NaN
51741   NaN
51758   NaN
52070   NaN
52157   NaN
52541   NaN
52542   NaN
52563   NaN
52711   NaN
52883   NaN
53023   NaN
53174   NaN
53213   NaN
53277   NaN
53436   NaN
53533   NaN
53666   NaN
53726   NaN
53825   NaN
53876   NaN
53983   NaN
54424   NaN
54535   NaN
54624   NaN
54734   NaN
Name: previous_year_rating, Length: 339, dtype: float64

In [132]:
X = [] 
X = new_df.values.tolist()


In [133]:
k=0
for row in X:
    if math.isnan(row[3]) == True:
            k= k+1
print(k)

4124


In [134]:
test_df_na = new_df.dropna(subset=['education'])
test_df_na['education'].value_counts()
test_df_na = test_df_na.fillna(value='Bachelor\'s', axis=0)
test_df_na['education'].value_counts()

Bachelor's          39078
Master's & above    14925
Below Secondary       805
Name: education, dtype: int64

In [135]:
for row in X:
    if math.isnan(row[3]) == True and row[8] == 1:
        row[3] = 5.0
    elif math.isnan(row[3]) == True :
        row[3] = 3.0
        

In [136]:
import numpy as np
X = np.array(X)
labels = X[:,-1]
X = X[:,:-1]

X.shape

(54808, 8)

In [137]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

lbl = LabelEncoder()
enc = OneHotEncoder(sparse=False)
X[:,0] = lbl.fit_transform(X[:,0])

In [138]:
integer_encoded = X[:,0].reshape(len(X[:,0]), 1)
onehot_encoded = enc.fit_transform(integer_encoded)
onehot_encoded = np.array(onehot_encoded)
onehot_encoded
X
new_X = np.append(X[:,1:],onehot_encoded, axis = 1)
new_X.shape

(54808, 16)

In [139]:
lbl = LabelEncoder()
enc = OneHotEncoder(sparse=False)
new_X[:,0] = lbl.fit_transform(new_X[:,0])
integer_encoded = new_X[:,0].reshape(len(new_X[:,0]), 1)
onehot_encoded = enc.fit_transform(integer_encoded)
onehot_encoded = np.array(onehot_encoded)
onehot_encoded
new_X = np.append(new_X[:,1:],onehot_encoded, axis = 1)
new_X.shape

(54808, 18)

In [140]:
np.unique(new_X[:,1])

array(['1.0', '2.0', '3.0', '4.0', '5.0'], dtype='<U32')

In [141]:
lbl = LabelEncoder()
enc = OneHotEncoder(sparse=False)
new_X[:,1] = lbl.fit_transform(new_X[:,1])
integer_encoded = new_X[:,1].reshape(len(new_X[:,1]), 1)
onehot_encoded = enc.fit_transform(integer_encoded)
onehot_encoded = np.array(onehot_encoded)
onehot_encoded
new_X = np.append(np.delete(new_X, 1, axis = 1),onehot_encoded, axis = 1)
new_X.shape

(54808, 22)

In [142]:
new_X.shape

(54808, 22)

In [32]:
from sklearn import preprocessing

min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(new_X)
new_X = x_scaled

c:\users\kanwal\miniconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype <U32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


In [143]:
from sklearn.model_selection import train_test_split

X_train, X_valid , y_train, y_test = train_test_split(new_X, labels, test_size =0.1, shuffle=True)

In [101]:
X_train.shape

(49327, 19)

In [102]:
y_train.shape

(49327,)

In [25]:
from sklearn.ensemble import RandomForestClassifier 
classifier = RandomForestClassifier()
classifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [37]:
from sklearn import tree 
classifier = tree.DecisionTreeClassifier()
classifier.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [38]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

tprediction = classifier.predict(X_valid)

print(accuracy_score(y_test, tprediction))
print(classification_report(y_test, tprediction))
print(confusion_matrix(y_test, tprediction))

0.9430760810071155
             precision    recall  f1-score   support

          0       0.95      0.99      0.97      5009
          1       0.85      0.41      0.56       472

avg / total       0.94      0.94      0.93      5481

[[4974   35]
 [ 277  195]]


In [35]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

cprediction = classifier.predict(X_valid)

print(accuracy_score(y_test, cprediction))
print(classification_report(y_test, cprediction))
print(confusion_matrix(y_test, cprediction))



0.942893632548805
             precision    recall  f1-score   support

          0       0.95      0.99      0.97      5009
          1       0.85      0.41      0.55       472

avg / total       0.94      0.94      0.93      5481

[[4974   35]
 [ 278  194]]


In [41]:
from sklearn.svm import SVC

model = SVC(C=10, kernel='rbf')
model.fit(X_train, y_train)

SVC(C=10, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [42]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

prediction = model.predict(X_valid)

print(accuracy_score(y_test, prediction))
print(classification_report(y_test, prediction))
print(confusion_matrix(y_test, prediction))


0.946360153256705
             precision    recall  f1-score   support

          0       0.94      1.00      0.97      5009
          1       0.99      0.38      0.55       472

avg / total       0.95      0.95      0.94      5481

[[5007    2]
 [ 292  180]]


In [43]:
from sklearn.svm import SVC

model = SVC(C=10, kernel='rbf' , gamma=0.1)
model.fit(X_train, y_train)

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

prediction = model.predict(X_valid)

print(accuracy_score(y_test, prediction))
print(classification_report(y_test, prediction))
print(confusion_matrix(y_test, prediction))


0.9454479109651523
             precision    recall  f1-score   support

          0       0.95      1.00      0.97      5009
          1       0.96      0.38      0.55       472

avg / total       0.95      0.95      0.93      5481

[[5001    8]
 [ 291  181]]


In [144]:
from sklearn.svm import SVC

model = SVC()
model.fit(X_train, y_train)

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

prediction = model.predict(X_valid)

print(accuracy_score(y_test, prediction))
print(classification_report(y_test, prediction))
print(confusion_matrix(y_test, prediction))


0.9430760810071155
             precision    recall  f1-score   support

          0       0.94      1.00      0.97      5006
          1       0.99      0.35      0.51       475

avg / total       0.95      0.94      0.93      5481

[[5004    2]
 [ 310  165]]


In [187]:
prediction = model.predict(X_valid)

In [188]:
prediction[0]

'0'

In [191]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, prediction)

0.9520160554643313

In [145]:
test_df = pd.read_csv('test.csv')

In [146]:
test_df.head()
new_test_df = test_df.drop(columns =['employee_id' , 'recruitment_channel', 'age' ,'gender','region'], axis = 0)
new_test_df.head()

department   education  no_of_trainings  previous_year_rating  \
0         Technology  Bachelor's                1                   NaN   
1                 HR  Bachelor's                1                   3.0   
2  Sales & Marketing  Bachelor's                1                   1.0   
3        Procurement  Bachelor's                3                   2.0   
4            Finance  Bachelor's                1                   4.0   

   length_of_service  KPIs_met >80%  awards_won?  avg_training_score  
0                  1              1            0                  77  
1                  5              0            0                  51  
2                  4              0            0                  47  
3                  9              0            0                  65  
4                  7              0            0                  61

In [250]:
len(new_test_df['department'].unique())

9

In [251]:
len(new_test_df['region'].unique())

34

In [147]:
new_test_df.isnull().sum()

department                 0
education               1034
no_of_trainings            0
previous_year_rating    1812
length_of_service          0
KPIs_met >80%              0
awards_won?                0
avg_training_score         0
dtype: int64

In [255]:
X_test_1 = [] 
X_test_1 = new_test_df.values.tolist()

k=0
for row in X_test_1:
    if math.isnan(row[3]) == True:
            k= k+1
print(k)

for row in X_test_1:
    if math.isnan(row[3]) == True:
        row[3] = 3
        
k=0
for row in X_test_1:
    if math.isnan(row[3]) == True:
            k= k+1
print(k)


1812
0


In [256]:
X_test_1[0]

['Technology', 'region_26', 1, 3, 1, 1, 0, 77]

In [258]:
X_test_1 = np.array(X_test_1)
X_test_1.shape

(23490, 8)

In [259]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

lbl = LabelEncoder()
enc = OneHotEncoder(sparse=False)
X_test_1[:,0] = lbl.fit_transform(X_test_1[:,0])

integer_encoded = X_test_1[:,0].reshape(len(X_test_1[:,0]), 1)
onehot_encoded = enc.fit_transform(integer_encoded)
onehot_encoded = np.array(onehot_encoded)
onehot_encoded
X_test
new_X_test = np.append(X_test_1[:,1:],onehot_encoded, axis = 1)
new_X_test[0]

array(['region_26', '1', '3', '1', '1', '0', '77', '0.0', '0.0', '0.0',
       '0.0', '0.0', '0.0', '0.0', '0.0', '1.0'], dtype='<U32')

In [260]:


lbl = LabelEncoder()
enc = OneHotEncoder(sparse=False)
X_test_1[:,0] = lbl.fit_transform(X_test_1[:,0])
integer_encoded = X_test_1[:,0].reshape(len(X_test_1[:,0]), 1)
onehot_encoded = enc.fit_transform(integer_encoded)
onehot_encoded = np.array(onehot_encoded)
onehot_encoded
new_X_test = np.append(new_X_test[:,1:],onehot_encoded, axis = 1)
new_X_test[0]

array(['1', '3', '1', '1', '0', '77', '0.0', '0.0', '0.0', '0.0', '0.0',
       '0.0', '0.0', '0.0', '1.0', '0.0', '0.0', '0.0', '0.0', '0.0',
       '0.0', '0.0', '0.0', '1.0'], dtype='<U32')

In [261]:
new_X_test.shape

(23490, 24)

In [262]:
pred_test = model.predict(new_X_test)

In [263]:
pred_test

array(['0', '0', '0', ..., '0', '0', '1'], dtype='<U17')

In [264]:
for i in pred_test:
    file = open('result.txt' , 'a+')
    file.write(i+'\n')